{% set name = "secimport" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/secimport-{{ version }}.tar.gz
  sha256: ea8de9547f02cd0e64aebdcd84393a4eb36769e505b3ee0ede808eba90edfcc9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - numpy
    - python >=3.6,<4.0
    - pyyaml >=6.0

test:
  imports:
    - secimport
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/avilum/secimport
  summary: A sandbox/supervisor for python modules.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
