{% set name = "secimport" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/secimport-{{ version }}.tar.gz
  sha256: 1667e2274b5f9ecdbcb87759c14c33c4f85291a490e0c5592bb1baba6ed97449

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - fire >=0.4.0,<0.5.0
    - python >=3.6,<4.0
    - pyyaml >=6.0,<7.0

test:
  imports:
    - secimport
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/avilum/secimport
  summary: A sandbox/supervisor for python modules.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
