{% set name = "secimport" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/secimport-{{ version }}.tar.gz
  sha256: 2b81bba9ef99d27cc4e00577d4877adfa2eb4f0612aafa3dbc51b38212de683d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7,<4.0
  run:
    - fire >=0.4,<0.6
    - python >=3.7,<4.0
    - pyyaml >=6.0.0,<7.0.0

test:
  imports:
    - secimport
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/avilum/secimport
  summary: A sandbox/supervisor for python modules.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
