{% set name = "secimport" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/secimport-{{ version }}.tar.gz
  sha256: ad7083a25f58fc857231941ff8732cc5c0f3bd9e54d0ab30ce5ca53038b1c607

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - fire >=0.4.0,<0.5.0
    - python >=3.6,<4.0
    - pyyaml >=6.0,<7.0

test:
  imports:
    - secimport
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/avilum/secimport
  summary: A sandbox/supervisor for python modules.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
