{% set name = "secimport" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/secimport-{{ version }}.tar.gz
  sha256: 6748540c911beb4aed5bdc192ffa139c275507d0f526cf6a25ccfc4c2531a29c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - secimport = secimport.cli:main

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - fire >=0.4,<0.7
    - python >={{ python_min }},<4.0
    - pyyaml >=6.0.0,<7.0.0

test:
  imports:
    - secimport
  commands:
    - pip check
    - secimport --help
  requires:
    - pip
    - python {{ python_min }}
about:
  home: https://github.com/avilum/secimport
  summary: A sandbox/supervisor for python modules.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
